"""Adding relationship between Users and Bookings

Revision ID: f7e955f29104
Revises: 77b34bcaa2ce
Create Date: 2023-08-28 15:10:07.621445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7e955f29104'
down_revision: Union[str, None] = '77b34bcaa2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
